In [6]:
import numpy as np

Q1

In [7]:
assign1=np.arange(9)
assign1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
assign1=assign1.reshape(3,3)
assign1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q2

In [9]:
assign2=np.arange(10)
assign2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
assign2.size

10

In [13]:
for i in range(assign2.size):
    if assign2[i]%2!=0:
        assign2[i]=-1

In [14]:
assign2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q3

In [28]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
o1=np.array([])
o2=np.array([])

In [36]:
for i in range(x.size):
    if(x[i]>y[i]):
        o1=np.append(o1,[i])
    elif(x[i]==y[i]):
        o2=np.append(o2,[i])

In [37]:
print(o1)
print(o2)

[1. 2. 4. 5. 6. 7. 8. 9.]
[0.]


Q4

In [38]:
assign4= np.arange(100).reshape(5,-1)

In [41]:
assign4[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

Additional questions
Q1

In [47]:
x=np.random.randint(30,40,size=(10))
x

array([34, 33, 36, 34, 31, 32, 36, 39, 37, 39])

Q2 

In [56]:
a = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 10])) 
b = np.array(([7, 8, 10] ,[4, 5, 6], [1, 2, 3]))

i.

In [58]:
c=a+b
e=a-b

In [59]:
print(c)
print(e)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


ii.

In [63]:
print(np.sum(a))
print(np.sum(b,axis=0))
print(np.sum(c,axis=1))

46
[12 15 19]
[31 30 31]


iii.

In [64]:
d=np.dot(a,b)
d

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

iv.

In [65]:
e=np.sort(c)
e

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

v.

In [66]:
np.transpose(e)

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])